name       : xwd
version    : 1.0.6
release    : 3
source     :
    - https://www.x.org/releases/individual/app/xwd-1.0.6.tar.gz : ff01f0a4b736f955aaf7c8c3942211bc52f9fb75d96f2b19777f33fff5dc5b83
license    :
    - MIT
component  : xorg.apps
summary    : |
    X.Org Applications: xwd
description: |
    X.Org Applications: xwd
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xkbfile)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
