name       : xwd
version    : 1.0.7
release    : 6
source     :
    - https://www.x.org/releases/individual/app/xwd-1.0.7.tar.gz : 1c5e86806234a96a29c90be1872128293c6def5ba69ecb70e161efe325e2ba03
license    :
    - MIT
component  : xorg.apps
summary    : |
    X.Org Applications: xwd
description: |
    X.Org Applications: xwd
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xkbfile)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
