name       : xwd
version    : 1.0.8
release    : 9
source     :
    - https://www.x.org/releases/individual/app/xwd-1.0.8.tar.gz : 066d10a1b66a47efd7caa7d7aa670c0c26ff90c8408f0e30b4dfb29dcb39d4c4
license    : MIT
component  : xorg.apps
summary    : |
    X Window System window dumping utility
description: |
    Xwd allows X users to store window images in a specially formatted dump file. This file can then be read by various other X utilities for redisplay, printing, editing, formatting, archiving, image processing, etc. The target window is selected by clicking the pointer in the desired window. The keyboard bell is rung once at the beginning of the dump and twice when the dump is completed.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xkbfile)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
